name: Update README

on:
  schedule:
    - cron: "* * * * *" # Ejecutar cada minuto
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }} # Asegúrate de usar el nombre correcto del secreto

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Especifica la versión de Python que deseas usar

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run YouTube Script
        env:
          YOUTUBE_API_KEY: ${{ env.YOUTUBE_API_KEY }}
        run: python update_readme.py # Ejecutar el script de Python

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest YouTube videos" || echo "No changes to commit"
          git push || echo "No changes to push"
