name: Update README

on:
  schedule:
    # - cron: "0 0 * * *" # Ejecutar una vez al día a la medianoche (UTC)
    - cron: "* * * * *" # Ejecutar cada minuto
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          npm install

      - name: Run YouTube Script
        env:
          YOUTUBE_API_KEY: ${{ env.YOUTUBE_API_KEY }}
        run: node updateReadme.mjs

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest YouTube videos"
          git push
