name: Update README

on:
  schedule:
    - cron: "* * * * *" # Ejecutar cada minuto
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts" # Usar la versión LTS de Node.js

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies with Bun
        run: bun install

      - name: Run YouTube Script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: bun run updateReadme.mjs # Asegúrate de que tu script sea ejecutable con Bun

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest YouTube videos" || echo "No changes to commit"
          git push || echo "No changes to push"
